title: Srinithi Mohan
description: CS student @ UNC-Chapel Hill — cybersecurity, quant finance, AI/ML, robotics, software dev.

markdown: kramdown
plugins:
  - jekyll-seo-tag

collections:
  projects:
    output: false

